name: Run swap tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/*.py
